version: '3.5'

services:
  appartment_searchs:
    build:
      context: ../..
      dockerfile: ./deploy/local/Dockerfile
    command: ["rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - ../../code:/opt/appartment_search
      - ../../deploy:/opt/appartment_search/deploy
    environment:
      RAILS_ENV: development
      MASTER_PASSWORD: ${MASTER_PASSWORD}
      POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  appartment-searchs-db:
    container_name: appartment-searchs-db
    image: postgres:11
    volumes:
      - type: volume
        source: appartment_searchs_db
        target: /var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  appartment_searchs_db:
