 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/visit_comments", type: :request do
  
  # VisitComment. As you add validations to VisitComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      VisitComment.create! valid_attributes
      get visit_comments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      visit_comment = VisitComment.create! valid_attributes
      get visit_comment_url(visit_comment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_visit_comment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      visit_comment = VisitComment.create! valid_attributes
      get edit_visit_comment_url(visit_comment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new VisitComment" do
        expect {
          post visit_comments_url, params: { visit_comment: valid_attributes }
        }.to change(VisitComment, :count).by(1)
      end

      it "redirects to the created visit_comment" do
        post visit_comments_url, params: { visit_comment: valid_attributes }
        expect(response).to redirect_to(visit_comment_url(VisitComment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new VisitComment" do
        expect {
          post visit_comments_url, params: { visit_comment: invalid_attributes }
        }.to change(VisitComment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post visit_comments_url, params: { visit_comment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested visit_comment" do
        visit_comment = VisitComment.create! valid_attributes
        patch visit_comment_url(visit_comment), params: { visit_comment: new_attributes }
        visit_comment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the visit_comment" do
        visit_comment = VisitComment.create! valid_attributes
        patch visit_comment_url(visit_comment), params: { visit_comment: new_attributes }
        visit_comment.reload
        expect(response).to redirect_to(visit_comment_url(visit_comment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        visit_comment = VisitComment.create! valid_attributes
        patch visit_comment_url(visit_comment), params: { visit_comment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested visit_comment" do
      visit_comment = VisitComment.create! valid_attributes
      expect {
        delete visit_comment_url(visit_comment)
      }.to change(VisitComment, :count).by(-1)
    end

    it "redirects to the visit_comments list" do
      visit_comment = VisitComment.create! valid_attributes
      delete visit_comment_url(visit_comment)
      expect(response).to redirect_to(visit_comments_url)
    end
  end
end
